name: snake_game
description: A snake game made in Flutter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.7.6
  flame: ^1.6.0
  event_bus: ^2.0.0
  lucide_icons: ^0.105.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true